### ISSUE TITLE
cursor position restoration

### ISSUE THREAD

**Issue by pmp-p** [salt-die/nurses_2#11]
Hi, while testing https://pygame-web.github.io/showroom/pythongit.html?-i#src/test_nurses2.py
i noticed that cursor does not come back to repl after entering text in "textbox"

Since i included nurses_2 in an external async loop i'm not sure  cursor save/restore is on me or nurses_2 ( which i think it should) or i just did things wrong [test code](https://github.com/pygame-web/showroom/blob/main/src/test_nurses2.py)

**Comment by Froloket64** [comment]
I'm pretty sure it's the interactive environment's (e.g. tty, REPL) task to take care of switching input focus, since the app only knows about its own "window" it's running in.

**Comment by pmp-p** [comment]
but that's not about focus ( which probably could be simply selected from mouse position), that's just about text cursor position.

basically should *all* nurses_2 operation pass  not be enclosed like that ?
# save cursor
"\x1b7\x1b[?25l"

#nurses_2 draw 

# restore cursor
"\x1b8\x1b[?25h"

**Comment by pmp-p** [comment]
> I'm not very well versed on ansi escape sequences, so I'm not sure what does the ESC7, ESC8 part do

- hide cursor to avoid drawing artifacts ( very visible on slow lines eg 1200 bauds videotex ), save cursor position.
- render. .
- restore cursor position and show it again.

As a typical rendering engine would save context, prepare device to draw and then restore things as they were. At first glance, I considered nurses as an **embeddable** rendering engine but maybe i'm wrong. 
But i would be sad as most of TUI are app centric frameworks that cannot fill that void ( often using ncurses and/or future/threads ). I tested too much of them to adapt for WebAssembly and especially WASI ( which limit itself to text output for now) and none would fit with ease.

**Comment by salt-die** [comment]
Cursor should be restored when nurses exits, since everything nurses does is in the alternate screen buffer. Main screen cursor shouldn't change.  

The web terminal showing a `>>>` underneath the nurses output worries me that it didn't enter the alternate screen correctly.
And backspace in the textbox seems to move the entirety of the line on the terminal implying that the terminal is still in cooked mode and not raw mode. 

Cursor is always hidden unless a text input widget has focus. Though I didn't see a cursor in the web terminal at all.
Note that `_Root.render` *does* save cursor position and restore it after a screen render: https://github.com/salt-die/nurses_2/blob/main/nurses_2/widgets/_root.py#L126-L140

So I'm curious about these three things on the web terminal: 
* Does it enter the alternate screen buffer?
* Does it enter raw mode?
* Are hide (`\x1b[?25l`)/show (`\x1b[?25h`)/save (`\x1b7`)/restore (`\x1b8`) cursor ansi escapes working?

**Comment by pmp-p** [comment]
> Note that _Root.render does save cursor position and restore it after a screen render

yes it is only on textinput field that cursor was not restored everything else suggest save/restore cursor works normally.

it does not enter alternate screen buffer,  it is just alternating buffered operations from python and nurses rendering pass in the asyncio loop

There's no raw mode since there no IOCTL/termios available on emscripten/wasi. As a workaround i kept stdin fd flushing on line feed so python is happy, and one duplicating stdin but char by char ( changed one line in nurses to read from it ), that per char fd is the only one to receive mouse infos to avoid polluting python's stdin.

i think xterm.js has no cursor when drawing ( and use webgl for that) and yes afaik all vt100 is implemented correctly,  and a few exotic parts of vt420 ( sixel ).

**Comment by salt-die** [comment]
> i guess echo of the textbox is also enclosed in the render() block save/restore too ?
The `render_children` call (https://github.com/salt-die/nurses_2/blob/main/nurses_2/widgets/_root.py#L105) traverses the entire widget tree to fill the buffer array. That includes the textbox. 

For text inputs, the cursor is moved to match the "virtual cursor" of the widget and so subsequent save/restores will keep the cursor on the text widget. What I might do is draw a virtual cursor for text input instead of using the real terminal cursor; this would fix this issue.

I'll need to think about what to do for terminals that can't enter raw mode.

**Comment by salt-die** [comment]
Newest release text input widgets no longer use terminal cursor.  Let me know if this helps.

**Comment by pmp-p** [comment]
looks good

**Comment by pmp-p** [comment]
i think there's a regression on the virtual/real cursor thing on current tree

**Comment by salt-die** [comment]
Interesting. I removed save/restore cursor on render since cursor should be hidden. I can add it back; will update soon.

**Comment by pmp-p** [comment]
thanks it's fixed 

btw why not apply [black formatting](https://github.com/psf/black/) to the whole source tree ?

**Comment by salt-die** [comment]
Source was formatted with black here: [3988a1a: Linted, Blacked, Isorted, Faster, Stronger, Better.](https://gitkraken.dev/link/dnNjb2RlOi8vZWFtb2Rpby5naXRsZW5zL2xpbmsvci9hZDQxNmNhOWZhMzZjMWQ1NDZiNjJhN2RjOGJkOTQ5ODNhZWMwMWUxL2MvMzk4OGExYWYzM2Q1OTVlNjc2ZWQ3MDBkZGQyOGVlODA5MzUyMTZhZT91cmw9aHR0cHMlM0ElMkYlMkZnaXRodWIuY29tJTJGc2FsdC1kaWUlMkZiYXRncmwuZ2l0).
But recently black has been replaced with ruff and I'm using some pydocstyle options that require more formatting changes. Coming soon.
