### ISSUE TITLE
Multiple keypresses at once?

### ISSUE THREAD

**Issue by 2231puppy** [salt-die/nurses_2#2]
With the `key_presses.py` file, if you hold down 2 keys at once, it prints both keys once, and then continues to print the second key pressed, and only that key. I'd expect it to maybe alternate between printing the first and second key pressed. Is this possible to implement? I'd be happy to put in a PR if you could point me in the right direction. I love this library, thanks so much for your work!

Example: I pressed and held `k`, and then pressed and held `l`.
```
Got Press: KeyPressEvent(key='k', mods=Mods(alt=False, ctrl=False, shift=False))
Got Press: KeyPressEvent(key='l', mods=Mods(alt=False, ctrl=False, shift=False))
Got Press: KeyPressEvent(key='l', mods=Mods(alt=False, ctrl=False, shift=False))
Got Press: KeyPressEvent(key='l', mods=Mods(alt=False, ctrl=False, shift=False))
...
```

**Comment by salt-die** [comment]
I'm not sure this is possible. This is just how stdin fills when multiple keys are pressed -- the last pressed key will repeat. One can test this with just a normal terminal prompt:

https://user-images.githubusercontent.com/53280662/185728247-a3d37fb1-9496-4d7a-b902-4e8de173216b.mp4

On windows, KEY_EVENT_RECORD should give key up events (reference: https://docs.microsoft.com/en-us/windows/console/key-event-record-str), so maybe in theory we could emulate multiple keys being pressed. This behavior would be inconsistent with linux though.

There are some alternatives to nurses_2 input though. I've hooked up, say `pynput` to nurses and other terminal projects before so that key down and key up events can be polled. I think this requires root on linux though. Here's an example of pynput + nurses_2 + nes emulator in the terminal:

https://user-images.githubusercontent.com/53280662/185728452-9fa94b28-af59-43ae-b7e6-1041fff59d40.mp4

**Comment by 2231puppy** [comment]
Alright, thanks for the thoughts. pynput looks promising, so I think I'll go with that. It appears it only requires root on Linux. I'm building a little terminal game, so if someone *really* wants Linux support, they should know how to use sudo :)

Again, thanks so much for this library. It's so cool!
