### ISSUE TITLE
[Question] Logging errors

### ISSUE THREAD

**Issue by Froloket64** [salt-die/nurses_2#7]
Is there a way to log Python exceptions that occur (more specifically `NameError`s)? When they occur my app just freezes and stops responding.
Whenever I try to pipe the `python` command (e.g. `python FILE | tee log.txt`) or use a different way to redirect output (`python FILE 2&> log.txt`, `echo $(python FILE) > log.txt`, etc.) I get the following error (the same with all methods above):
```
Traceback (most recent call last):
  File "/home/froloket/Code/Python/DD Launcher/main.py", line 32, in <module>
    Launcher(custom_path, mods_path, dd_path).run() # My code
  File "/home/froloket/.local/lib/python3.10/site-packages/nurses_2/app.py", line 135, in run
    asyncio.run(self._run_async())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/froloket/.local/lib/python3.10/site-packages/nurses_2/app.py", line 154, in _run_async
    self.root = root = _Root(
  File "/home/froloket/.local/lib/python3.10/site-packages/nurses_2/widgets/_root.py", line 30, in __init__
    self.size = env_out.get_size()
  File "/home/froloket/.local/lib/python3.10/site-packages/nurses_2/io/output/vt100.py", line 65, in get_size
    cols, rows = os.get_terminal_size()
OSError: [Errno 25] Inappropriate ioctl for device
```
I know this might be not a `nurses_2`-specific issus and that's why I marked it as **[Question]**, but I haven't found anything on this problem, so I can't confirm if it occurs only with `nurses_2` or any async python program. Either way, I think it's too important to discard.

**Comment by salt-die** [comment]
If you try to pipe the output to some file, nurses_2 will fail when it tries to do terminal control operations (like getting the size of the terminal) because there is no terminal. You can save the output of a nurses_2 app to a file if you provide an ascii_cast path. The output will be saved in asciicast format (see: https://github.com/asciinema/asciinema/blob/develop/doc/asciicast-v2.md).

But for errors, while the app is running stderr is being redirected to a text buffer. Relevant code:
https://github.com/salt-die/nurses_2/blob/main/nurses_2/app.py#L129-L139. You can implement your on `run` method to save this output to a file instead of printing it after the app exits.

**Comment by Froloket64** [comment]
Oh, wait, I just realized that you can (provided you're using **Bash** or some other **UNIX shell**) redirect only the stderr using `python FILE 2> log.txt` (Checked, it works!). Sorry for the inconvenience, I somehow forgot about that...

But thanks for the general/platform-independant solution nonetheless!
